/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public DeepstreamClient

    public static void main(String[] args) {
        DeepstreamClient client = new DeepstreamClient("<Your app url here>");

    }
}
